# Generated by Django 5.2 on 2025-04-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RTCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_number', models.CharField(max_length=100)),
                ('surnoc', models.CharField(max_length=100)),
                ('hissa', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('hobli', models.CharField(max_length=100)),
                ('taluk', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('screenshot_path', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RTC Data',
                'verbose_name_plural': 'RTC Data',
            },
        ),
    ]
