# Generated by Django 5.2 on 2025-04-26 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100)),
                ('period_text', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=100)),
                ('year_text', models.CharField(max_length=100)),
                ('image_data', models.BinaryField(blank=True, null=True)),
                ('screenshot_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rtc_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.rtcdata')),
            ],
            options={
                'verbose_name': 'RTC Document',
                'verbose_name_plural': 'RTC Documents',
            },
        ),
    ]
